name: job_timer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  fast_ui_kit: ^1.0.10
  flutter_modular: ^6.0.4+1
  modular_bloc_bind: ^2.0.0-beta.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  isar: ^3.1.0+1
  path_provider: ^2.1.1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/