// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVWRL1L1m9ortC2btaLEwmKppKDBIQ9VM',
    appId: '1:38672665921:android:51bd546186b022ec8c25c0',
    messagingSenderId: '38672665921',
    projectId: 'timer-app-dw7',
    storageBucket: 'timer-app-dw7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCSqaK5bUcMzEQV5j635qbxFgXtX1o-1k',
    appId: '1:38672665921:ios:4e75d8c8550297ad8c25c0',
    messagingSenderId: '38672665921',
    projectId: 'timer-app-dw7',
    storageBucket: 'timer-app-dw7.appspot.com',
    iosBundleId: 'br.com.jobtimer.jobTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCSqaK5bUcMzEQV5j635qbxFgXtX1o-1k',
    appId: '1:38672665921:ios:048efb14181881b48c25c0',
    messagingSenderId: '38672665921',
    projectId: 'timer-app-dw7',
    storageBucket: 'timer-app-dw7.appspot.com',
    iosBundleId: 'br.com.jobtimer.jobTimer.RunnerTests',
  );
}
